### PR TITLE
Pull Request for Next.js Cape Software Community Blog Project

### PR DESCRIPTION
**Pull request by smngvlkz**
## Overview

This pull request contains the entire code base for the Next.js Cape Software Community Blog Project. The project is aimed at migrating the Cape Software Community website to a static website using Next.js and Markdown for blog posts.

## OBJECTIVES COMPLETED

- Created the Next.js project structure.
- Set up Markdown to HTML conversion for original content.
- Styled the original content using Tailwind CSS.
- Added a new blog link to store and view all the blog posts. Old and new
- Restricted the latest section to only show a maximum of 3 posts (Hence the new Blog page)
- Added a few more features
- Added a detailed README with project setup instructions, a TODO list for future features, and a note about the project's design for easy contributions.

## Testing

The blog runs successfully in a local development environment. Each blog post from the `content` directory is correctly converted from Markdown to HTML and displayed on the page with the applied styles.

## Future Work

This is the initial commit of the project. Future work will include making the blog responsive for mobile and smaller screens, adding a search feature, setting up authentication, and allowing users to subscribe and unsubscribe. I will also request more help in implementing these features as I still have school work to complete too.

I look forward to your feedback!

### CODE REVIEW

**Comment by BenSchZA** [comment]
@smngvlkz great work! I'll leave some feedback here.

There is an issue with the formatting of the dates that cause the app to crash on my machine:
image

For the learning resources page, I'd remove the images—this will be too much manual overhead to maintain, unless the previews are automatically generated from the URL metadata in future.

The website will need a header and footer for navigation throughout the website.

For features like search and subscription, I'd see if there's anything off-the-shelf, but otherwise I don't expect these to be implemented within the scope of this bounty. I'd suggest to remove these features in the meantime, and focus on:
- UI/UX improvements (read more, back home, layout, etc.—I can give more feedback here in a second pass if necessary)
- Display images in a gallery (see current website)
- Allow commenting (maybe Disqus) and sharing of content (i.e. blog posts should be populated with the necessary metadata to be shared on social media with previews etc.)

**Comment by smngvlkz** [comment]
@BenSchZA Thank you!

I’ve taken note of the issue you pointed out and I’m on it. My apologies for any inconvenience caused. Rest assured, it’s going to be fixed in the next update.

Regarding the URL metadata. I’ll make the necessary adjustments.

Your suggestion about revisiting other features is well-received. I’ll focus on the current priorities first and circle back to the other features later.

I’m looking forward to more of your feedback on your next pass.

I’m all ears for any further suggestions or clarifications you might have. Again, thank you

**Comment by smngvlkz** [comment]
@BenSchZA I have made the following updates:
- Fixed the formatting issue.
- Improved the UI/UX
- Integrated Disqus into the blog post component to allow commenting and sharing of content.
- Refactored the header and footer components to be separate from index.js, allowing them to be reused across the site.
- Disabled the subscribe and sign-in buttons
- Images can be displayed in a gallery
- Removed the images/logos from the learning resource page but kept them in the images folder just in case we decide to use them in the future. 

These changes aim to improve the user experience by utilizing Disqus's built-in features, and making the header and footer reusable. The subscribe and sign-in features have been temporarily disabled as per your instructions and will be revisited in the future.

Please note for Disqus, I will need usernames of anyone you might want to be added as moderators, for now I am the only moderator.

**Comment by BenSchZA** [comment]
Thanks for the update and detailed comment! I've left some further UI/UX feedback in a document to address: https://docs.google.com/document/d/1nRBCKIN1tCE-Ay3Omjuf003YZquahJZeclf9oeczzbQ/edit?usp=sharing. I'd be happy to discuss these first if anything is unclear or you don't agree with any of the feedback.

**Comment by smngvlkz** [comment]
@BenSchZA, I've implemented a series of enhancements and bug fixes to the website, aimed at improving both the design and user experience.

Here are the key changes:

- The website's title has been centered, enhancing alignment and readability.

- I've resolved the issue where elements were overlaying each other inappropriately. The content is now centered, the navbar has been fixed, and additional spacing has been introduced between content sections.

- Comments are now above the READ MORE section

- Blog post cards have been made clickable, allowing users to access the full blog post by clicking anywhere on the card.

- Menu and close icons have been added to improve website navigation. The website has been made responsive, ensuring a seamless user experience across various screen sizes.

- Updated blog page to display posts in cards and lay them out in a gallery. 

- Adjusted "Read more" button positioning

These changes, taken together, significantly improve the overall user experience and functionality of the website.

While I believe these updates fulfill the requirements of the bounty, I welcome further feedback. This project has been an invaluable learning experience for me. The guidance and mentorship I've received have been exceptional, and I'm eager to continue learning and improving

**Comment by BenSchZA** [comment]
@smngvlkz I've reviewed the latest updates and I'm happy to award the bounty. I'll approve and merge the PR 🎉

**Comment by smngvlkz** [comment]
@all-contributors please add @BenSchZA for being an awesome mentor. please add @smngvlkz  for the code

**Pull request merged**
